[package]
name = "spectrum-network"
version = "0.1.0"
edition = "2021"
rust-version = "1.65.0"

[features]
test_peer_punish_too_slow = []
integration_tests = []

[dependencies]
algebra-core = { version = "0.1.0", path = "../algebra-core" }
spectrum-crypto = { version = "0.1.0", path = "../spectrum-crypto" }
spectrum-ledger = { version = "0.1.0", path = "../spectrum-ledger" }
libp2p = { version = "0.52.0", features = ["noise", "yamux", "secp256k1", "serde"] }
libp2p-identity = "0.2.*"
futures = "0.3.21"
async-std = { version = "1.10.0", features = ["attributes"] }
unsigned-varint = { version = "0.7.1", features = ["futures", "asynchronous_codec"] }
asynchronous-codec = "0.6.0"
pin-project = "1.0.10"
void = "1.0.2"
thiserror = "1.0.34"
log = "0.4.17"
log4rs = "1.2.0"
rand = "0.8.5"
rand_chacha = "0.3.1"
wasm-timer = "0.2.5"
serde = { version = "1.0.147", features = ["derive"] }
ciborium = "0.2.1"
smallvec = "1.10.0"
derive_more = "0.99.17"
either = { version = "1.8.1", features = ["serde"] }
sha2 = "0.10.6"
blake2 = "0.10.6"
elliptic-curve = { version = "0.13.*", features = ["serde", "arithmetic"] }
k256 = { version = "0.13.*", features = ["serde"] }
libsecp256k1 = "0.7.1"
group = "0.13.*"
nonempty = "0.8.1"
higher = "0.2.0"
tokio = {version = "1.28.*", features = ["time", "rt", "macros", "rt-multi-thread", "tracing"] }
console-subscriber = "0.1.10"
tracing = "0.1.37"
tracing-subscriber = "0.3"
async-trait = "0.1.68"
rocksdb = "0.21.0"

[dev-dependencies]
libp2p = { version = "0.52.0", features = ["noise", "yamux", "async-std", "tcp"] }
log4rs_test_utils = {version = "0.2.3", featuers = ["test_logging"]}
base16 = "0.2.1"
serde_yaml = "0.9.21"
itertools = "0.10.5"
