name = "spectrum/vault"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'spectrum/vault'"

[repository]
user = "spectrum"
project = "vault"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.3.0"
source = "github"
