[package]
name = "spectrum-crypto"
version = "0.1.0"
edition = "2021"
rust-version = "1.65.0"

[dependencies]
rand = "0.8.5"
smallvec = "1.10.0"
derive_more = "0.99.17"
either = "1.8.1"
base16 = "0.2.1"
sha2 = "0.10.6"
blake2 = "0.10.6"
thiserror = "1.0.34"
serde = { version = "1.0.147", features = ["derive"] }
serde_with = "3.0.0"
elliptic-curve = "0.13.*"
k256 = { version = "0.13.*", features = ["serde"] }
libp2p-identity = { version = "0.2.*", features = ["peerid", "secp256k1"] }
libsecp256k1 = "0.7.1"
async-trait = "0.1.68"